### ISSUE TITLE
SurveillanceLogsInterface.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

### ISSUE THREAD

**Issue by alfiosalanitri** [neelkanthk/laravel-surveillance#8]
Hi, can you update this Class? Thanks.
Deprecation Notice: Class Neelkanth\Laravel\Surveillance\Interfaces\SurveillanceLogInterface located in ./vendor/neelkanthk/laravel-surveillance/src/Interfaces/SurveillanceLogsInterface.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///opt/psa/var/modules/composer/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by neelkanthk** [comment]
@alfiosalanitri Yes. I am aware of that. I am working on fixing it in 1-2 days. I will notify you once the fix gets released.
Thanks.

**Comment by alfiosalanitri** [comment]
Thanks, great job.  This is an amazing package.

**Comment by neelkanthk** [comment]
@alfiosalanitri 

This has been fixed in the version 1.3.

You can update the package using `composer require neelkanthk/laravel-surveillance`
or
In your `composer.json`  add ` "neelkanthk/laravel-surveillance": "^1.3" ` and run `composer update`

Thanks.

**Comment by neelkanthk** [comment]
Hi @alfiosalanitri 

I hope you are still using this package.

There is an announcement. I have released **Laravel Surveillance UI** package which provides a Graphical UI for Laravel Surveillance and integrates within existing application.

Link: [Laravel Surveillance UI](https://github.com/neelkanthk/laravel-surveillance-ui)

Thanks.
